### ISSUE TITLE
Buying out of stock item

### ISSUE THREAD

**Issue by jackthomas00** [Bui-Alex46/Smart-Vending-Machine#9]
Currently you are not prevented from buying an item even if the "number_in_stock" is zero or less. Need a way to prevent button press from going though or message saying the item is out of stock. Should not be able to go below zero items.

**Comment by Alex-R-Projects** [comment]
pd_device_commission[df_device_commission['X']<0] = False

try using this
 or possibly using numpy 

import numpy as np
df = pd.DataFrame({'col1': list('ABBC'), 'col2': list('ZZXY')})

df['color'] = np.where(df['col2'] == 'Z', 'green', 'red') # this selects the collumn, but we can manipulate the collumn to not allow the value to go below 0
